#!/usr/bin/env bash
#

input="$1"
name="$2"
name="${name:-recording}-$(date -Ihours).txt"
wav_temp="$(mktemp).wav"

ffmpeg -i $input -ar 16000 -ac 1 -c:a pcm_s16le $wav_temp
whisper_exec -f $wav_temp -m $XDG_DATA_HOME/whisper/ggml-base.en.bin -ovtt

cp "$wav_temp.vtt" ~/Desktop/$name
cat $HOME/Desktop/$name | awk 'NR%10 == 0; !/.* -->.*/' | sed '/^$/d' | sed 's/\(.*\)-->\(.*\)/Start of block: \1/' | pbcopy
